package dockerregistry.internal.storage;

public class UnknownException extends StorageException {

    public UnknownException(Throwable cause) {
        super(cause);
    }
}
